USE COURSE; 

CREATE TABLE SHORT_COURSE 
( 
COURSE_ID VARCHAR(10) NOT NULL, 
COURSE_DESCRIPTION CHAR(50) NOT NULL, 
COURSE_PRICE INT,  
PRIMARY KEY (COURSE_ID)
); 

CREATE TABLE CAMPUS 
(
CAMPUS_ID VARCHAR(10) NOT NULL, 
CAMPUS_NAME CHAR(30) NOT NULL, 
CAMPUS_ADDRESS VARCHAR(30) NOT NULL 
PRIMARY KEY (CAMPUS_ID)
);

CREATE TABLE COURSE_REGISTRATION 
(
COURSE_ID VARCHAR(10) NOT NULL, 
CAMPUS_ID VARCHAR(10) NOT NULL, 
SPACES_AVAILABLE INT NOT NULL,
FOREIGN KEY (COURSE_ID) REFERENCES SHORT_COURSE (COURSE_ID), 
FOREIGN KEY (CAMPUS_ID) REFERENCES CAMPUS (CAMPUS_ID)
); 