USE COURSES; 

CREATE TABLE SHORT_COURSE 
(
COURSE_ID VARCHAR(10) NOT NULL, 
COURSE_DESCRIPTION VARCHAR(80) NOT NULL, 
COURSE_PRICE DECIMAL(10,2) NOT NULL, 
PRIMARY KEY (COURSE_ID)
); 

CREATE TABLE CAMPUS 
(
CAMPUS_ID VARCHAR(8) NOT NULL, 
CAMPUS_NAME CHAR(50) NOT NULL, 
CAMPUS_ADDRESS VARCHAR(50) NULL, 
PRIMARY KEY (CAMPUS_ID)
); 

CREATE TABLE COURSE_DESCRIPTION 
(
SPACES_AVAILABLE INT NOT NULL,
COURSE_ID VARCHAR(10) NOT NULL, 
CAMPUS_ID VARCHAR(8) NOT NULL,
FOREIGN KEY (COURSE_ID) REFERENCES SHORT_COURSE (COURSE_ID), 
FOREIGN KEY (CAMPUS_ID) REFERENCES CAMPUS (CAMPUS_ID)
); 