USE DVD_RENTALS; 

CREATE TABLE KAYAKS 
( 
KAYAK_ID INT NOT NULL, 
KAYAK_TYPE CHAR(30) NOT NULL, 
KAYAK_MODEL VARCHAR(20) NOT NULL, 
MANUFACTURER CHAR(20) NOT NULL, 
PRIMARY KEY (KAYAK_ID)
); 

CREATE TABLE CUSTOMER 
( 
CUST_ID VARCHAR(10) NOT NULL, 
CUST_FNAME CHAR(20) NOT NULL, 
CUST_SNAME CHAR(20) NOT NULL, 
CUST_ADDRESS VARCHAR(50) NOT NULL,
CUST_CONTACT INT NOT NULL, 
PRIMARY KEY (CUST_ID)
); 

CREATE TABLE UPGRADES 
(
UPGRADE_ID INT NOT NULL, 
UPGRADE_WORK CHAR(100) NOT NULL, 
UPGRADE_DATE DATE NOT NULL, 
UPGRADE_HRS INT NOT NULL, 
PRIMARY KEY (UPGRADE_ID)
);

CREATE TABLE KAYAK_UPGRADES 
(
KAYAK_UPGRADE_NUM INT NOT NULL, 
KAYAK_UPGRADE_DATE DATE NOT NULL, 
KAYAK_UPGRADE_AMT DECIMAL, 
KAYAK_ID INT, 
CUST_ID VARCHAR(10),
UPGRADE_ID INT,
PRIMARY KEY (KAYAK_UPGRADE_NUM),
FOREIGN KEY (KAYAK_ID) REFERENCES KAYAKS (KAYAK_ID),
FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (CUST_ID), 
FOREIGN KEY (UPGRADE_ID) REFERENCES UPGRADES (UPGRADE_ID)
); 
